name: Publish to Maven

on: [ workflow_dispatch ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Pull Tags
        run: git fetch --all --tags
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 1.16
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew publish
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_URL: ${{ secrets.MAVEN_URL }}